on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'phpunit.xml.dist'

  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'phpunit.xml.dist'

name: easy-coding-standard

jobs:
  psalm:
    uses: php-forge/actions/.github/workflows/ecs.yml@main
    secrets:
      AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
    with:
      os: >-
        ['ubuntu-latest']
      php: >-
        ['8.1', '8.2']
