on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'psalm.xml'

  push:
    branches: ['main']
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'psalm.xml'

name: mutation test

jobs:
  mutation:
    uses: php-forge/actions/.github/workflows/roave-infection.yml@main
    secrets:
      AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
      STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
    with:
      debug: true
      os: >-
        ['ubuntu-latest']
      options: --threads=2 --ignore-msi-with-no-mutations --only-covered -s --log-verbosity=all
      php: >-
        ['8.1']
