on:
  - pull_request
  - push

name: static analysis

jobs:
  psalm:
    uses: php-forge/reusable-actions/.github/workflows/psalm.yml@main
    with:
      os: >-
        ['ubuntu-latest']
      php: >-
        ['8.0', '8.1']
